# Generated by Django 2.1.7 on 2019-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleinfo',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
