"""'重新命名name'

Revision ID: d1f1a273d45a
Revises: 9f57081a39a2
Create Date: 2019-04-04 22:07:26.464004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1f1a273d45a'
down_revision = '9f57081a39a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('nick_name', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['nick_name'])
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))

    # op.drop_constraint(None, 'roles', type_='unique')
    # upgrade的时候更新了name，在上面的upgrade方法中添加了唯一约束
    # 降级的时候需要手动在donwgrade函数中去掉这个约束，将None变为'nick_name'
    op.drop_constraint('nick_name', 'roles', type_='unique')

    op.create_index('name', 'roles', ['name'], unique=True)
    op.drop_column('roles', 'nick_name')
    # ### end Alembic commands ###
